# Generated by Django 5.1.2 on 2024-12-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
